// Synthetic fixture mirroring AppLayout/AppSidebar/TablePageLayout public DOM.
const glyph = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5"><rect x="4" y="4" width="16" height="16" rx="3"/><path d="M4 10h16M10 10v10"/></svg>';
const routes = [['dashboard','仪表盘'],['ops','运维监控'],['users','用户管理'],['groups','分组管理'],['channels/pricing','渠道定价'],['channels/monitor','渠道监控'],['subscriptions','订阅管理'],['accounts','账号管理'],['plugins','插件管理'],['proxies','代理管理'],['announcements','公告管理'],['redeem','兑换码'],['promo-codes','优惠码'],['orders','订单管理'],['usage','使用记录'],['audit-logs','审计日志'],['settings','系统设置']];
document.querySelector('#admin-nav').innerHTML = routes.map(([path,label]) => `<a class="sidebar-link" href="/admin/${path}">${glyph}<span class="sidebar-label">${label}</span></a>`).join('');
const accounts = Array.from({length:12},(_,i) => ({name:['Claude 生产账号','OpenAI 团队账号','Gemini 共享资源'][i%3]+` ${String(i+1).padStart(2,'0')}`,platform:['Claude','OpenAI','Gemini'][i%3],group:['企业服务','开发测试','默认分组'][i%3],status:i===4?'冷却中':'正常',quota:32+(i*13)%65}));
function rows(){const q=document.querySelector('#account-query')?.value.toLowerCase()||'';const p=document.querySelector('#platform')?.value||'';const s=document.querySelector('#status')?.value||'';const data=accounts.filter(a=>(a.name.toLowerCase().includes(q))&&(!p||a.platform===p)&&(!s||a.status===s));document.querySelector('tbody').innerHTML=data.length?data.map((a,i)=>`<tr><td><input type="checkbox" aria-label="选择 ${a.name}"></td><td><div class="account-cell"><span class="account-icon">${a.platform[0]}</span><div>${a.name}<small>ID ${1042+i} · OAuth 授权</small></div></div></td><td><span class="badge">${a.platform}</span></td><td><span class="badge">${a.group}</span></td><td><span class="status ${a.status==='正常'?'':'warn'}">${a.status}</span></td><td>10</td><td><span style="font-size:11px">${a.quota}%</span><div class="quota"><i style="width:${a.quota}%"></i></div></td><td style="font-size:11px;color:#8293a8">09-28 10:${String(i*3).padStart(2,'0')}</td><td><button class="row-action" data-edit>编辑</button></td></tr>`).join(''):'<tr><td colspan="9" class="empty-cell">没有匹配的账号</td></tr>';document.querySelector('#record-count').textContent=`共 ${data.length} 条记录`;document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=()=>document.querySelector('#account-dialog').showModal());}
function render(){const page=location.pathname.split('/admin/')[1]||'accounts';document.querySelectorAll('.sidebar-link').forEach(a=>a.classList.toggle('sidebar-link-active',a.getAttribute('href')===location.pathname));const label=routes.find(r=>r[0]===page)?.[1]||'个人资料';document.querySelector('header h1').textContent=label;const main=document.querySelector('main');if(page==='dashboard'){main.innerHTML=`<div class="dashboard-grid">${[['服务账号','128','112 个正常运行'],['今日请求','24,680','较昨日 +12.8%'],['今日 Token','18.6M','用量持续更新'],['活跃用户','386','今日新增 12 人']].map(([l,n,d])=>`<div class="card metric"><p>${l}</p><strong>${n}</strong><small>${d}</small></div>`).join('')}</div><div class="card overview"><h2>请求趋势 <small>演示数据 · 最近 24 小时</small></h2><div class="bars">${[24,18,22,15,31,40,36,45,58,66,54,60,83,69,78,86,70,64,53,60,72,90,80,66].map(h=>`<i style="height:${h}%"></i>`).join('')}</div><div class="overview-footer"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:00</span></div></div>`;return;}main.innerHTML=`<div class="table-page-layout"><div class="layout-section-fixed toolbar"><span class="toolbar-label">${label}<small>全部账号 · 12</small></span><span class="spacer"></span><button class="btn btn-secondary" id="refresh">↻ 刷新</button><button class="btn btn-primary" id="add-account">＋ 添加账号</button></div><div class="layout-section-fixed filters"><input class="input" id="account-query" aria-label="搜索账号" placeholder="搜索账号名称…"><select class="input" id="platform" aria-label="服务平台"><option value="">全部平台</option><option>Claude</option><option>OpenAI</option><option>Gemini</option></select><select class="input" id="status" aria-label="账号状态"><option value="">全部状态</option><option>正常</option><option>冷却中</option></select><span class="preview-note">皮肤预览 · 数据均为演示</span></div><div class="layout-section-scrollable"><div class="card table-scroll-container"><div class="table-wrapper"><table><thead><tr><th><input type="checkbox" id="check-all" aria-label="全选账号"></th><th>账号名称</th><th>平台</th><th>所属分组</th><th>状态</th><th>优先级</th><th>窗口用量</th><th>最近使用</th><th>操作</th></tr></thead><tbody></tbody></table></div></div></div><div class="layout-section-fixed pagination"><span id="record-count"></span><span class="spacer"></span><span>20 条 / 页</span><button class="btn btn-secondary" disabled>‹</button><button class="btn btn-primary">1</button><button class="btn btn-secondary" disabled>›</button></div></div>`;rows();document.querySelector('#account-query').oninput=rows;document.querySelector('#platform').onchange=rows;document.querySelector('#status').onchange=rows;document.querySelector('#refresh').onclick=rows;document.querySelector('#add-account').onclick=()=>document.querySelector('#account-dialog').showModal();document.querySelector('#check-all').onchange=e=>document.querySelectorAll('tbody input').forEach(c=>c.checked=e.target.checked);}
document.addEventListener('click',e=>{const a=e.target.closest('a[href^="/"]');if(a){e.preventDefault();history.pushState({},'',a.href);render();document.querySelector('.sidebar').classList.add('-translate-x-full');}});
document.querySelector('#native-theme').onclick=()=>document.documentElement.classList.toggle('dark');
document.querySelector('#native-collapse').onclick=()=>document.querySelector('.sidebar').classList.toggle('w-[72px]');
document.querySelector('.mobile-toggle').onclick=()=>document.querySelector('.sidebar').classList.toggle('-translate-x-full');
window.addEventListener('popstate',render);render();
